#!/bin/bash -l
#SBATCH -J {name}
#SBATCH -o {output}.o%j
#SBATCH -p {account}
#SBATCH --mem-per-cpu=4GB
#SBATCH -t 04:00:00
#SBATCH -n 20

module load {mpi_module}
module load {fort_compile_module}
conda deactivate
conda activate Barry
echo "Activated python"
echo `which python`

cd {path}
mpirun python precompute_mpi.py --model {model} --reconsmoothscale {reconsmoothscale} --redshift {z} --om {om} --h0 {h0} --ob {ob} --ns {ns} --mnu {mnu}
