#!/bin/bash -l
#SBATCH -p {partition}
#SBATCH -J ptgenerator
#SBATCH --mem-per-cpu=4GB
#SBATCH -t 04:00:00
#SBATCH -o jobs/zlog.o%j
#SBATCH -n 20

module load {mpi_module}
conda deactivate
conda activate {conda_env}
echo "Activated python"
echo `which python`

cd {path}
/opt/openmpi/bin/mpirun python PT_generator.py --om_resolution 101 --h0_resolution 1 --reconsmoothscale {reconsmoothscale} --redshift {z} --om {om} --h0 {h0} --ob {ob} --ns {ns}
